services:
  mysql:
    image: mysql:8.0
    container_name: dpre-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
      MYSQL_DATABASE: skeleton
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

networks:
  back-end-network:
    external: true

volumes:
  mysql-data:
    name: mysql-data
    driver: local
